# -*- coding: utf-8 -*-
"""100days of python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Errz36DDVtBcrgFAn_BoBcqQzcMD9OY
"""

# 1. Python output python  is case sensitive language
print("Hellow world")

print("dipsikha",1,2.3,True)

"""2. Data Types"""

print(8)
# 1*10^308
print(1e309)

# Decimal/flot
print(8.99)

# boolean
print(True)
print(False)

# text/string
print("dipsikha")

# complex
print(5+6j)

# list -> c-> Array
print([1,2,3,4,5])

# tuple
print((1,2,3,4,5))

# set
print({1,2,3,4,5})

# dictionary
print({'name':'dipsikha','roll':2033890})

# type
type('helow')

"""3. Variable"""

# static vs dynamic typing
# static vs dynamic binding

# dynamic typing=you donot tell the datatype of variable
a=5
b=7
print(a+b)

# static typing = you define the datatype of variable
# int a=5 c++,c

# python support dynamic binding means
a=4
print(a)
a='dips'
print(a)

# c,c++ support static binding
# int a=5 canot be char a='dips'

a,b,c=1,2,3
print(a,b,c)

a=b=c=5
print(a,b,c)

"""4.keywords and identifiers"""

# keywords=Python keywords are reserved words that have special meanings and purposes in the language's syntax.
# compiler convert all english lang to 0,1 and interpriter convert line by line english lang to 0,1

# identifiers= name create is identifires
# You can't start with a digit
name1='nitish'
print(name1)
# you can use special chars -> __
first_name='dipsikha'
print(first_name)
# identifires can not be keywords



"""5. User Input"""

# static vs dynamic software
input('enter your name')

# take input from user and store them in varible
num1=int(input('enter your number1'))
num2=int(input('enter your number'))
# add the 2 variable
result=num1+num2
# print the result
print(result)
print(type(num1))

# string is universal data formate

"""6.Type conversion"""

# implicit vs explicit
print(5+5.6)
print(type(5),type(5.6))

# explicit
# str -> int
# int(6+5j)
str(5)



"""7.Literals"""

#  Binary literal
a=0b1010
print(a)

# decimal literal
b=100
print(b)

# Octal literal
c=0o310
print(c)

# hexadecimal literal
d=0x12c
print(d)

# float literal
float_1=10.5
float_2=1.5e2
print(float_1,float_2)

# complex literal
x=3.14j
print(x,x.imag,x.real)

# string
string='this is string'
string="diis"
string="""hhgf"""
unicode=u"\u00dcnic\u00f6de"
unicode=u"\U0001f600\U0001F606"
raw_str=r"raw\nstring"

print(string)
print(unicode)
print(raw_str)

a=True+4
b=False+10
print("a:",a)
print("b:",b)

a=None
print(a)



"""8.Operations"""

